# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b28efcda8b2b129483db3461bb82d71db24a632955c446a3fc9b2d5b6ac8e8ffa333e2d4a6cafacfb53682506036632505e8307799fa7eb9c7ef01b84630e5b

test:
  secret_key_base: 6df9a5043ebe082b25217bae323de7172aa7d18c68fed1412766c68c94c1066674edafe07fdef6cf7b456369a11c937b5472753938f6112a38a7916abfde78e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
